---
version: '2'

services:
  konekto_backoffice:
    image: 266564908162.dkr.ecr.ap-southeast-1.amazonaws.com/backoffice_service
    hostname: konekto_backoffice
    container_name: konekto_backoffice
    ports:
      - "8099:8099"
    environment:
      DB_URL: jdbc:mysql://tokobook-staging.culeg0tcenww.ap-southeast-1.rds.amazonaws.com:3306/backofficedb?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      DB_USERNAME: tokobook_admin
      DB_PASSWORD: emlRnEmkvUTGxtAZdChk